name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Django Check
      run: |
        python manage.py check

    - name: Run Tests
      run: |
        python manage.py test

    - name: Install Linting Tool
      run: |
        pip install flake8

    - name: Run Linter
      run: |
        flake8 .
            